site_name: Vixen Shell Documentation
site_url: https://vixen-shell.github.io

nav:
  - Welcome: index.md
  - Install: install.md
  - Features:
    - Introduction: features/intro.md
    - Manage: features/manage.md
  - Commands: commands.md

theme:
  name: material
  logo: assets/vixen_logo.svg
  favicon: assets/vixen_logo.svg
  icon:
    annotation: material/plus-circle
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: true
      
repo_url: https://github.com/vixen-shell
